### PR TITLE
add open graph meta

### PR DESCRIPTION
**Pull request by radiokills**
Test with https://developers.facebook.com/tools/debug/

### CODE REVIEW

**Comment by mrfoto** [comment]
Supr, ampak tole bo delal sam na home pageu. More bit dinamicno is pagea/posta ven, ce pa ni pa nek default - recimo to k je zdej.

**Comment by mrfoto** [comment]
Also, twitter cards. This should be a good starting point: https://github.com/mrfoto/mrfoto.github.io/blob/master/_includes/_open-graph.html

**Comment by otobrglez** [comment]
@radiokills + @mrfoto Lahk tole zapremo če je done?

**Comment by mrfoto** [comment]
Sej ni done

**Comment by otobrglez** [comment]
@radiokills state of this thing?

**Comment by mfilej** [comment]
Closing due to inactivity, feel free to reopen if anything changes.

**Pull request closed without merging**
