### PR TITLE
Add 404 page

### PR DESCRIPTION
**Pull request by mfilej**
2015-06-15 at 08 27

Any suggestions for the copy? For now I just copied it from rails.

### CODE REVIEW

**Comment by mrfoto** [comment]
Jz bi dal isto, k smo mel prej https://github.com/RubySlovenia/RubySlovenia.github.io/blob/20b9a72196e0bd69d2885fe79ce3ae87fc9ba9a4/404.html#L51

Pa mogoče bi dal večje fonte, da se bl poudar. As small heading maybe?

**Comment by mfilej** [comment]
A kej takega?

Al si mislu dat tekst gor na rdeče ozadje? Ker to ne vem kako naredi. :sweat_smile:

**Comment by mrfoto** [comment]
Zakaj si dal HTML če si pa v markdownu? :smile: Drgač pa ja, neki tazga

**Comment by mfilej** [comment]
Copypasta :persevere:

Fixed!

**Comment by mrfoto** [comment]
:+1:

**Pull request merged**
