### PR TITLE
March meetup

### PR DESCRIPTION
**Pull request by danes**
This is the march meetup recap.

Some items are still todo:

I've asked @lenart for embeddable slides from speakerdeck or slideshare..

I'm also not sure when/where will the video be available?

@mrfoto: Do you have any photos for the gallery and for the background image?

### CODE REVIEW

**Comment by mrfoto** [comment]
No one knows about the video. I'll ask the guy.
Photos (pick and choose): https://dl.dropboxusercontent.com/u/88844/rugmarec.zip

**Comment by danes** [comment]
@mrfoto: I've added the photos and the slides, the only thing missing is the video.

You can go ahead and merge this, and we can add the video later.

**Comment by danes** [comment]
@mrfoto: The video is up, you can go ahead and merge this

**Comment by mrfoto** [comment]
:tada:

**Pull request merged**
