### PR TITLE
Update congributing.md file

### PR DESCRIPTION
**Pull request by knagode**
Make it easier to understand how to contribute for newbies

### CODE REVIEW

**Comment by mrfoto** [comment]
https://github.com/RubySlovenia/RubySlovenia.github.io/pull/38#discussion_r51449435

**Comment by lenart** [comment]
Great congribution ;)

**Comment by knagode** [comment]
Haha lol :)

**Comment by otobrglez** [comment]
What is the state of this PR?

**Comment by otobrglez** [comment]
@knagode thanks. this was merged.

**Pull request closed without merging**
