### PR TITLE
Video site

### PR DESCRIPTION
**Pull request by otobrglez**
Just an idea...

Lets have `/video` where all videos are collected.

What u say?

### CODE REVIEW

**Comment by mrfoto** [comment]
We could do it via tag/category i guess. Otherwise we're duplicating stuff. Or, if we go this way, we should then just link from blog posts.

**Comment by otobrglez** [comment]
It is painful going over all posts to see all the videos. PPL should be able to easily enjoy our content. That is the problem that this PR / idea is trying to solve.

a) We do it like this. Or with jekyll collections, or with YT playlist?
b) Explain your idea a bit more....

**Comment by mrfoto** [comment]
I'm saying that this way is OK, but then we should go through our posts and link to the video on this page. So every video should have it's own h2 or h3 so it would be easy to link to it via anchors.

**Comment by mfilej** [comment]
Closing due to inactivity, feel free to reopen if anything changes.

**Pull request closed without merging**
